name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Step 1: Checkout the code from the repo
    - uses: actions/checkout@v4

    # Step 2: Setup Node.js using the specified version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: SGWebsite/package-lock.json # Ensure the path matches your project structure

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        cd SGWebsite
        npm install

    # Step 4: Build the project using Vite
    - name: Build the project
      run: |
        cd SGWebsite
        npm run build-only

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        cd SGWebsite
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
